// .agent/skills/sci-grid/examples/solid-provider.tsx
import { Component } from 'solid-js';
import { VeloGridSolid } from '@velosci-grid/solid';
import type { IDataGridProvider } from '@velosci-grid/core';

export const SolidGrid: Component = () => {
  const provider: IDataGridProvider = {
    getRowCount: () => 2000,
    getColumnCount: () => 100,
    getCellData: (r, c) => `S-${r}-${c}`,
    getHeader: (c) => ({ name: `H${c}` })
  };

  return (
    <div style="height: 600px; width: 100%;">
      <VeloGridSolid 
        provider={provider} 
        config={{ headerHeight: 40 }} 
      />
    </div>
  );
};

// .agent/skills/sci-grid/examples/vue-provider.vue
<script setup lang="ts">
import { VeloGridVue } from '@velosci-grid/vue';
import type { IDataGridProvider, GridConfig } from '@velosci-grid/core';

// Static provider definition
const provider: IDataGridProvider = {
  getRowCount: () => 1000,
  getColumnCount: () => 50,
  getCellData: (row, col) => `Vue ${row}x${col}`,
  getHeader: (col) => ({ name: `C${col}` })
};

const config: GridConfig = {
  headerHeight: 50,
  rowHeight: 30
};
</script>

<template>
  <div style="height: 600px; width: 100%;">
    <VeloGridVue :provider="provider" :config="config" />
  </div>
</template>
