// packages/angular/src/index.ts
import { Component, ElementRef, Input, type OnChanges, type OnDestroy, type OnInit, type SimpleChanges, ViewChild } from '@angular/core';
import { VeloGrid } from '@velosci-grid/core';
import type { GridConfig, IDataGridProvider } from '@velosci-grid/core';

/**
 * VeloGrid Angular Adapter
 * Enterprise-ready grid component for Angular applications.
 */
@Component({
  selector: 'velosci-grid',
  template: `<div #gridContainer style="width: 100%; height: 100%; min-height: 400px;"></div>`,
  standalone: true
})
export class VeloGridAngular implements OnInit, OnChanges, OnDestroy {
  @ViewChild('gridContainer', { static: true }) gridContainer!: ElementRef;
  
  @Input() provider!: IDataGridProvider;
  @Input() config: Partial<GridConfig> = {};

  private grid: VeloGrid | null = null;

  ngOnInit() {
    this.grid = new VeloGrid(this.gridContainer.nativeElement, this.provider, this.config);
  }

  ngOnChanges(changes: SimpleChanges) {
    if (!this.grid) return;

    if (changes['provider']) {
      this.grid.updateProvider(this.provider);
    }
    if (changes['config']) {
      this.grid.updateConfig(this.config);
    }
  }

  ngOnDestroy() {
    this.grid?.destroy();
    this.grid = null;
  }
}

// packages/solid/src/index.tsx
import { onMount, onCleanup, createEffect } from 'solid-js';
import { VeloGrid } from '@velosci-grid/core';
import type { GridConfig, IDataGridProvider } from '@velosci-grid/core';

interface VeloGridSolidProps {
  provider: IDataGridProvider;
  config?: Partial<GridConfig>;
  class?: string;
  style?: any;
}

/**
 * VeloGrid SolidJS Adapter
 * Fine-grained reactive wrapper for maximum performance.
 */
export const VeloGridSolid = (props: VeloGridSolidProps) => {
  let containerRef!: HTMLDivElement;
  let grid: VeloGrid | null = null;

  onMount(() => {
    grid = new VeloGrid(containerRef, props.provider, props.config || {});
  });

  onCleanup(() => {
    grid?.destroy();
  });

  createEffect(() => {
    grid?.updateProvider(props.provider);
  });

  createEffect(() => {
    grid?.updateConfig(props.config || {});
  });

  return (
    <div 
      ref={containerRef} 
      class={props.class} 
      style={{ width: '100%', height: '100%', ...props.style } as any} 
    />
  );
};
