// packages/react/src/index.tsx
import { useRef, useEffect, type CSSProperties } from 'react';
import { SciGrid } from '@sci-grid/core';
import type { GridConfig, IDataGridProvider } from '@sci-grid/core';

interface SciGridReactProps {
  provider: IDataGridProvider;
  config?: Partial<GridConfig>;
  className?: string;
  style?: CSSProperties;
  onSort?: (col: number, order: 'asc' | 'desc' | null) => void;
  onSelectionChange?: (info: any) => void;
}

/**
 * SciGrid React Adapter
 * High-performance data grid component for React applications.
 */
export const SciGridReact = ({ 
  provider, 
  config = {}, 
  className, 
  style, 
  onSort,
  onSelectionChange 
}: SciGridReactProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const gridRef = useRef<SciGrid | null>(null);

  useEffect(() => {
    if (containerRef.current) {
      gridRef.current = new SciGrid(containerRef.current, provider, {
        ...config,
        onSort,
        onSelectionChange
      });
    }
    return () => {
      gridRef.current?.destroy();
      gridRef.current = null;
    };
  }, []); // Only on mount

  // Handle provider updates
  useEffect(() => {
    if (gridRef.current) {
      gridRef.current.updateProvider(provider);
    }
  }, [provider]);

  // Handle config & callback updates
  useEffect(() => {
    if (gridRef.current) {
      gridRef.current.updateConfig({
        ...config,
        onSort,
        onSelectionChange
      });
    }
  }, [config, onSort, onSelectionChange]);

  return (
    <div 
      ref={containerRef} 
      className={className} 
      style={{ width: '100%', height: '100%', ...style }} 
    />
  );
};

// packages/solid/src/index.tsx
import { onMount, onCleanup, createEffect } from 'solid-js';
import { SciGrid } from '@sci-grid/core';
import type { GridConfig, IDataGridProvider } from '@sci-grid/core';

interface SciGridSolidProps {
  provider: IDataGridProvider;
  config?: Partial<GridConfig>;
  class?: string;
  style?: any;
}

/**
 * SciGrid SolidJS Adapter
 * Fine-grained reactive wrapper for maximum performance.
 */
export const SciGridSolid = (props: SciGridSolidProps) => {
  let containerRef!: HTMLDivElement;
  let grid: SciGrid | null = null;

  onMount(() => {
    grid = new SciGrid(containerRef, props.provider, props.config || {});
  });

  onCleanup(() => {
    grid?.destroy();
  });

  createEffect(() => {
    grid?.updateProvider(props.provider);
  });

  createEffect(() => {
    grid?.updateConfig(props.config || {});
  });

  return (
    <div 
      ref={containerRef} 
      class={props.class} 
      style={{ width: '100%', height: '100%', ...props.style } as any} 
    />
  );
};
